name: Prepare Node.JS and PNPM

description: Prepare Node.JS and PNPM

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24.12.0
        registry-url: 'https://registry.npmjs.org'

    - name: Install pnpm
      uses: pnpm/action-setup@v6
      id: pnpm-install
      with:
        run_install: false
